### ISSUE TITLE
Any case class with a parameter of `type` fails to be constructed by .extract

### ISSUE THREAD

**Issue by TsundereBug** [lift/framework#1937] opened 2018-01-28 06:09 UTC
**[Mailing List](https://groups.google.com/forum/#!forum/liftweb) thread:** https://groups.google.com/forum/#!topic/liftweb/CUdrn43OZK4

**[Example project](https://app.assembla.com/wiki/show/liftweb/Posting_example_code) link:** [discord.scala](https://github.com/DiscordScala/discord.scala)

Given any case class like

    case class Thingy(`type`: Long)

lift will throw an error saying it is unable to find a constructor.

**Comment by farmdawgnation** [comment] 2018-01-29 15:19
First time looking at your issues since I've been in front of a computer. Unfortunately, this is simply not the case:

```
@ case class Thingy(`type`: Long)
defined class Thingy

@ (("type" -> 102L)): JObject
res13: JObject = JObject(List(JField("type", JInt(102))))

@ res13.extract[Thingy]
res14: Thingy = Thingy(102L)
```

I've replied to the ML thread with a more detailed response than I was able to provide over the weekend and I suspect you're having a different issue.

Closing this as "not a bug." If you find other issues please do reach out, however.

**Closed by farmdawgnation** 2018-01-29 15:19 UTC
